CREATE OR REPLACE PROCEDURE TEST.MY_PROCEDURE (
   IN I_YEAR VARCHAR(4) DEFAULT NULL
) LANGUAGE SQLSCRIPT SQL SECURITY INVOKER AS 
BEGIN
  DECLARE V_TASK_NAME VARCHAR(100) := ::CURRENT_OBJECT_NAME;
  DECLARE V_TASK_STRT TIMESTAMP := CAST(NOW() AS DATETIME);
  DECLARE V_TASK_CNT INT = 0;

  TMPTBL = SELECT * 
           FROM TEST.MYTBL
           WHERE MY_YEAR >= :I_YEAR;

  INSERT INTO TEST.TEST_TBL
  SELECT * 
  FROM :TMPTBL;

  :V_TASK_CNT := ::ROWCOUNT;
END
